DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS schedules (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL,
  day INT NOT NULL,
  start_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users
    FOREIGN KEY(user_id)
    REFERENCES users(id)
    ON DELETE
);